language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - cd frontend && npm install
  - cd ../backend && npm install
script:
  - npm run start-test
  - cd ../frontend && npm test && npm run tslint && npm run typecheck