sudo: required
branches:
  only:
    - master
    - stable
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - cd backend && npm install
script:
  - npm start & npm test