branches:
  only:
    - master
    - stable
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - cd backend && npm install && cd ..
script:
  - chmod +x ./test.sh
  - sleep 25
  - cd backend && npm test