projects:
  app:
    schemaPath: src/schemas/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:9999
  db:
    schemaPath: src/generated-schema.graphql
    extensions:
      prisma: prisma/prisma.yml